version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - "3001:3001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/batch1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"