version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.18.0.2:5432/core_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - cat-network

networks:
  cat-network:
    external: true